/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026 Kevin Stenzel
 */

import APPS from '@libs/appconfig/constants/apps';

const CHAT_PATH = APPS.CHAT;

const CHAT_GROUP_TYPE_LOCATIONS = {
  CLASSES: 'classes',
  PROJECTS: 'projects',
  GROUPS: 'groups',
} as const;

const CHAT_CLASSES_LOCATION = CHAT_GROUP_TYPE_LOCATIONS.CLASSES;
const CHAT_PROJECTS_LOCATION = CHAT_GROUP_TYPE_LOCATIONS.PROJECTS;
const CHAT_GROUPS_LOCATION = CHAT_GROUP_TYPE_LOCATIONS.GROUPS;

const CHAT_CLASSES_PATH = `${CHAT_PATH}/${CHAT_CLASSES_LOCATION}`;
const CHAT_PROJECTS_PATH = `${CHAT_PATH}/${CHAT_PROJECTS_LOCATION}`;
const CHAT_GROUPS_PATH = `${CHAT_PATH}/${CHAT_GROUPS_LOCATION}`;

export {
  CHAT_PATH,
  CHAT_GROUP_TYPE_LOCATIONS,
  CHAT_CLASSES_LOCATION,
  CHAT_PROJECTS_LOCATION,
  CHAT_GROUPS_LOCATION,
  CHAT_CLASSES_PATH,
  CHAT_PROJECTS_PATH,
  CHAT_GROUPS_PATH,
};
